cache_type: DBPrune
max_warmup_steps: 8
warmup_interval: 1
Fn_compute_blocks: 8
Bn_compute_blocks: 8
max_continuous_cached_steps: 2
residual_diff_threshold: 0.12
enable_dynamic_prune_threshold: true
dynamic_prune_threshold_relax_ratio: 1.25
non_prune_block_ids: [8, 9, 10, 11, 12]
force_reduce_calibrator_vram: true
enable_taylorseer: false
enable_encoder_taylorseer: false
taylorseer_cache_type: residual
taylorseer_order: 1
