cache_type: DBPrune
max_warmup_steps: 1
residual_diff_threshold: 0.12
enable_dynamic_prune_threshold: true
dynamic_prune_threshold_relax_ratio: 1.25
enable_taylorseer: true
enable_encoder_taylorseer: true
taylorseer_cache_type: hidden_states
taylorseer_order: 1
