def activate_all_examples():
    from registers import flux_example  # noqa: F403, F401
    from registers import flux_fill_example  # noqa: F403, F401
    from registers import flux2_example  # noqa: F403, F401
    from registers import qwen_image_example  # noqa: F403, F401
    from registers import qwen_image_controlnet_example  # noqa: F403, F401
    from registers import qwen_image_edit_example  # noqa: F403, F401
    from registers import qwen_image_layered_example  # noqa: F403, F401
    from registers import skyreels_v2_example  # noqa: F403, F401
    from registers import ltx2_t2v_example  # noqa: F403, F401
    from registers import ltx2_i2v_example  # noqa: F403, F401
    from registers import wan_example  # noqa: F403, F401
    from registers import wan_i2v_example  # noqa: F403, F401
    from registers import wan_vace_example  # noqa: F403, F401
    from registers import ovis_image_example  # noqa: F403, F401
    from registers import zimage_example  # noqa: F403, F401
    from registers import longcat_image_example  # noqa: F403, F401
    from registers import longcat_image_edit_example  # noqa: F403, F401
    from registers import zimage_controlnet_example  # noqa: F403, F401
