cache_config:
  max_warmup_steps: 8
  warmup_interval: 2
  max_cached_steps: -1
  max_continuous_cached_steps: 2
  Fn_compute_blocks: 1
  Bn_compute_blocks: 0
  residual_diff_threshold: 0.12
  enable_dmd: true
  dmd_history: 6
  dmd_svd_precision: "medium"
quantize_config: 
  quant_type: "svdq_int4_r128_dq" 
  svdq_kwargs:
    quantize_device: "cuda"
    runtime_kernel: "v2"
    fused_mlp: true
  exclude_layers:  
    - "embedder"
    - "embed"
  verbose: false
