quantize_config: 
  components_to_quantize:
    transformer:
      quant_type: "float8"
      per_row: true
      exclude_layers:  
        - "embedder"
        - "embed"
    text_encoder_2:
      quant_type: "float8_weight_only"
      exclude_layers:  # e.g, T5EncoderModel for FLUX.1
        - "shared" 
        - "embed_tokens"
  verbose: false
